/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import dal.moduloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class CadastrarPaciente extends javax.swing.JInternalFrame {

     Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public CadastrarPaciente() {
        initComponents();
        conexao = moduloConexao.connector();
    }
    
    private void cadastrar (){
      String Sql = "INSERT INTO pacientes (nome) VALUES (?)";
      
      
        try{
            pst = conexao.prepareStatement(Sql);
          
            pst.setString(1,txtPacienteNome.getText());
            int adicionado =   pst.executeUpdate();
               
            if(adicionado > 0 ){
            JOptionPane.showMessageDialog(null,"Paciente Cadastrado");
            }
            
            else{
            JOptionPane.showMessageDialog(null,"Paciente nao cadastrado ");
            }
            
            }
        
        catch(Exception e ){
        JOptionPane.showMessageDialog(null, e);
        
    
    
    
    
} 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPacienteNome = new javax.swing.JTextField();
        btnCadastrarPaciente = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Paciente");

        jLabel1.setText("Nome ");

        txtPacienteNome.addActionListener(this::txtPacienteNomeActionPerformed);

        btnCadastrarPaciente.setText("Cadastrar");
        btnCadastrarPaciente.addActionListener(this::btnCadastrarPacienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarPaciente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnCadastrarPaciente)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPacienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteNomeActionPerformed

    private void btnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPacienteActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnCadastrarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPacienteNome;
    // End of variables declaration//GEN-END:variables
}
