/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import dal.moduloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinicius
 */
public class ConsultarHorarios extends javax.swing.JInternalFrame {
    
         
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form ConsultarHorarios
     */
    public ConsultarHorarios() {
        initComponents();
         conexao = moduloConexao.connector();
        populaTable();
    }
    
       public void populaTable (){
    
        String sql = "SELECT c.id_consulta AS 'ID Consulta', c.data_consulta AS 'Data', c.hora_consulta AS 'Hora', m.nome AS 'Médico', p.nome AS 'Paciente' FROM consultas c INNER JOIN medicos m ON c.id_medico = m.id_medico INNER JOIN pacientes p ON c.id_paciente = p.id_paciente";

try {
    pst = conexao.prepareStatement(sql);
    rs = pst.executeQuery();

    // Pegando o modelo da sua tabela Tbtelinha
    DefaultTableModel model = (DefaultTableModel) tbHorarios.getModel();
    
    // Limpa a tabela antes de preencher para não duplicar dados
    model.setNumRows(0);

    while (rs.next()) {
        
        model.addRow(new Object[]{
    rs.getString("ID Consulta"),   
    rs.getString("Data"),          
    rs.getString("Hora"),          
    rs.getString("Médico"),        
    rs.getString("Paciente")
        });
    }

} catch (Exception e) {
    // Usando o JOptionPane que corrigimos antes
    JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e);
}
    
        
    
    
    }
     
     public void deletar() {
    // No DELETE não se usa o "*"
    String sql = "DELETE FROM consultas WHERE id_consulta = ?";
    
    try {
        pst = conexao.prepareStatement(sql);
        pst.setString(1, txtHorarios.getText());
        
        // Para comandos que alteram o banco (DELETE, UPDATE, INSERT), use executeUpdate
        int apagado = pst.executeUpdate();
        
        if (apagado > 0) {
            JOptionPane.showMessageDialog(null, "Consulta removido com sucesso!");
            // Limpa o campo após deletar
            txtHorarios.setText(null);
            populaTable();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHorarios = new javax.swing.JTable();
        txtHorarios = new javax.swing.JTextField();
        btnDeletarHorarios = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Horarios");

        tbHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Consulta", "Data", "Hora", "Medico", "Paciente"
            }
        ));
        jScrollPane1.setViewportView(tbHorarios);

        txtHorarios.addActionListener(this::txtHorariosActionPerformed);

        btnDeletarHorarios.setText("Deletar");
        btnDeletarHorarios.addActionListener(this::btnDeletarHorariosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarHorarios))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletarHorarios))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorariosActionPerformed

    private void btnDeletarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarHorariosActionPerformed
        deletar();
    }//GEN-LAST:event_btnDeletarHorariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarHorarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHorarios;
    private javax.swing.JTextField txtHorarios;
    // End of variables declaration//GEN-END:variables
}
