/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import dal.moduloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinicius
 */
public class ConsultarPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarPaciente
     */
    public ConsultarPaciente() {
        initComponents();
        conexao = moduloConexao.connector();
        populaTable();
    }
    
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
     public void populaTable (){
    
        String sql = "SELECT * FROM pacientes";

try {
    pst = conexao.prepareStatement(sql);
    rs = pst.executeQuery();

    // Pegando o modelo da sua tabela Tbtelinha
    DefaultTableModel model = (DefaultTableModel) tbConsultarPacientes.getModel();
    
    // Limpa a tabela antes de preencher para não duplicar dados
    model.setNumRows(0);

    while (rs.next()) {
        
        model.addRow(new Object[]{
            rs.getString("id_paciente"),      
            rs.getString("nome"),
        });
    }

} catch (Exception e) {
    // Usando o JOptionPane que corrigimos antes
    JOptionPane.showMessageDialog(null, "Erro ao carregar tabela: " + e);
}
    
        
    
    
    }
     
     public void deletar() {
    // No DELETE não se usa o "*"
    String sql = "DELETE FROM pacientes WHERE id_paciente = ?";
    
    try {
        pst = conexao.prepareStatement(sql);
        pst.setString(1, txtID.getText());
        
        // Para comandos que alteram o banco (DELETE, UPDATE, INSERT), use executeUpdate
        int apagado = pst.executeUpdate();
        
        if (apagado > 0) {
            JOptionPane.showMessageDialog(null, "Usuário removido com sucesso!");
            // Limpa o campo após deletar
            txtID.setText(null);
            populaTable();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultarPacientes = new javax.swing.JTable();
        btnDeletarPaciente = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Pacientes");

        tbConsultarPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tbConsultarPacientes);

        btnDeletarPaciente.setText("Deletar");
        btnDeletarPaciente.addActionListener(this::btnDeletarPacienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarPaciente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletarPaciente)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarPacienteActionPerformed
        deletar();
    }//GEN-LAST:event_btnDeletarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsultarPacientes;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
