/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author vinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        exibirData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnMarcarConsulta = new javax.swing.JMenuItem();
        mnConsultarHorarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCadastrarPaciente = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnConsultarPaciente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnCadastrarMedico = new javax.swing.JMenuItem();
        mnConsultarMedico = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnUsuario = new javax.swing.JMenuItem();
        mnConsultarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("C059", 1, 14)); // NOI18N
        lblNome.setText("Nome");

        desktop.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("C059", 0, 36)); // NOI18N
        jLabel1.setText("Seja Bem-Vindo ");

        jLabel2.setText("versio 1.2.34w");

        lblData.setText("Data");

        jMenu1.setText("Agenda");

        mnMarcarConsulta.setText("Marcar Consulta");
        mnMarcarConsulta.addActionListener(this::mnMarcarConsultaActionPerformed);
        jMenu1.add(mnMarcarConsulta);

        mnConsultarHorarios.setText("Consultar Horarios");
        mnConsultarHorarios.addActionListener(this::mnConsultarHorariosActionPerformed);
        jMenu1.add(mnConsultarHorarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Paciente");

        mnCadastrarPaciente.setText("Cadrastrar novo Paciente");
        mnCadastrarPaciente.addActionListener(this::mnCadastrarPacienteActionPerformed);
        jMenu2.add(mnCadastrarPaciente);

        jMenuItem5.setText("Historico de Consultas");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        mnConsultarPaciente.setText("Consultar Pacientes");
        mnConsultarPaciente.addActionListener(this::mnConsultarPacienteActionPerformed);
        jMenu2.add(mnConsultarPaciente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Medico");

        mnCadastrarMedico.setText("Cadastrar Medico");
        mnCadastrarMedico.addActionListener(this::mnCadastrarMedicoActionPerformed);
        jMenu3.add(mnCadastrarMedico);

        mnConsultarMedico.setText("Consultar Medico");
        mnConsultarMedico.addActionListener(this::mnConsultarMedicoActionPerformed);
        jMenu3.add(mnConsultarMedico);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuario");

        mnUsuario.setText("Cadastrar Usuarios");
        mnUsuario.addActionListener(this::mnUsuarioActionPerformed);
        jMenu4.add(mnUsuario);

        mnConsultarUsuario.setText("Consultar Usuario");
        mnConsultarUsuario.addActionListener(this::mnConsultarUsuarioActionPerformed);
        jMenu4.add(mnConsultarUsuario);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblNome))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblData))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnConsultarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarHorariosActionPerformed
      ConsultarHorarios ch = new ConsultarHorarios();
      ch.setVisible(true);
      desktop.add(ch);
      
    }//GEN-LAST:event_mnConsultarHorariosActionPerformed

    private void mnMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMarcarConsultaActionPerformed
        try {
            Consultas ct = new Consultas();
            ct.setVisible(true);
            desktop.add(ct);
        } catch (ParseException ex) {
            System.getLogger(TelaPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mnMarcarConsultaActionPerformed

    private void mnCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarMedicoActionPerformed
        CadastrarMedico medico = new CadastrarMedico();
        medico.setVisible(true);
        desktop.add(medico);
    }//GEN-LAST:event_mnCadastrarMedicoActionPerformed

    private void mnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuarioActionPerformed
        CadastrarUsuario usuario = new CadastrarUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_mnUsuarioActionPerformed

    private void mnCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarPacienteActionPerformed
        CadastrarPaciente paciente = new CadastrarPaciente();
        paciente.setVisible(true);
        desktop.add(paciente);
    }//GEN-LAST:event_mnCadastrarPacienteActionPerformed

    private void mnConsultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarPacienteActionPerformed
        ConsultarPaciente consultap = new ConsultarPaciente();
        consultap.setVisible(true);
        desktop.add(consultap);
    }//GEN-LAST:event_mnConsultarPacienteActionPerformed

    private void mnConsultarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarMedicoActionPerformed
        ConsultarMedico cmedico = new ConsultarMedico();
        cmedico.setVisible(true);
        desktop.add(cmedico);
    }//GEN-LAST:event_mnConsultarMedicoActionPerformed

    private void mnConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarUsuarioActionPerformed
        ConsultarUsuario user = new ConsultarUsuario();
        user.setVisible(true);
        desktop.add(user);
    }//GEN-LAST:event_mnConsultarUsuarioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        HistoricoDeConsultas hc = new HistoricoDeConsultas();
        hc.setVisible(true);
        desktop.add(hc);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }
    
     public void exibirData(){
    
     LocalDate data = LocalDate.now()  ;
     DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
     String dataFormatada = data.format(formatador);
     
     lblData.setText(" "+dataFormatada + " ");
     
     
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblData;
    public javax.swing.JLabel lblNome;
    private javax.swing.JMenuItem mnCadastrarMedico;
    private javax.swing.JMenuItem mnCadastrarPaciente;
    private javax.swing.JMenuItem mnConsultarHorarios;
    private javax.swing.JMenuItem mnConsultarMedico;
    private javax.swing.JMenuItem mnConsultarPaciente;
    private javax.swing.JMenuItem mnConsultarUsuario;
    private javax.swing.JMenuItem mnMarcarConsulta;
    private javax.swing.JMenuItem mnUsuario;
    // End of variables declaration//GEN-END:variables
}
